services:
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      # We don't necessarily need to expose the DB port to the host machine anymore,
      # but it's useful for debugging with a GUI tool.
      - '3306:3306'
    environment:
      # Use the same variables to initialize the database
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    